### ISSUE TITLE
Agenda for March 17 Livestream

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/jeffgeerling-com#28]
- [x] Coronavirus/COVID-19 - we're all in it together!
  - [x] [My DevOps-related books are free this month](https://www.jeffgeerling.com/blog/2020/you-can-get-my-devops-books-free-rest-month)
  - [x] Worked on #18 and #22 to get a much faster local environment running.
    - [Revisiting Docker for Mac's performance using NFS volumes](https://www.jeffgeerling.com/blog/2020/revisiting-docker-macs-performance-nfs-volumes)
  - [x] [Drupal Local Development Survey (2020 edition)](https://www.jeffgeerling.com/blog/2020/2020-drupal-local-development-survey) is live! (442 responses so far)
  - [x] This repository is now PUBLIC and open source! But the things I write and publish on my site are still copyrighted ;)
  - [x] Discuss #4 and #7, which I worked on the past weekend
  - [x] Lets get back into theming; see #16 for basic stuff, adding library to front page!

**Comment by geerlingguy** [comment]
Got through some blog node page theming, figured out some libraries stuff. Didn't get to the /blog view though :(

**Comment by geerlingguy** [comment]
Episode 7 Livestream: https://www.youtube.com/watch?v=T7gSB9as6DM
