### ISSUE TITLE
Agenda for March 31 Livestream

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/jeffgeerling-com#41]
See previous agenda: #34 

  - [x] How's everyone doing?
  - [x] Last day to get Ansible for DevOps and Ansible for Kubernetes free! [More here](https://www.jeffgeerling.com/blog/2020/you-can-get-my-devops-books-free-rest-month).
  - [x] Last few days to complete [The 2020 Drupal Local Development Survey](https://www.jeffgeerling.com/blog/2020/2020-drupal-local-development-survey).
  - [x] Fixed views theme hook suggestion for page title (see https://github.com/geerlingguy/jeffgeerling-com/commit/cefcb94ab1c4757d16f6c25e039daa204c5f0e17#diff-d24779712900cdccdff38513aea14b90).
  - [x] Fixed annoying 'Field discovery failed' migration notices (see #8 and [thread](https://twitter.com/geerlingguy/status/1244834480642232322)).
  - [x] Upgrade Drupal core (see #35)?
  - [x] Finish theming blog post page (especially comments)
  - [ ] Add configuration split (see #40)?

**Comment by geerlingguy** [comment]
Finished most of the blog post theming issues... but still need to work on finishing up comments.

**Comment by geerlingguy** [comment]
Livestream video: https://www.youtube.com/watch?v=VwFMx8vm8Rs
