### ISSUE TITLE
Agenda for April 7 Livestream

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/jeffgeerling-com#43]
See previous agenda: #41

  - [x] How's everyone doing?
  - [x] [#DrupalCares](https://www.drupal.org/association/blog/drupalcares-sustaining-the-da-through-the-covid-19-crisis) - supporting the Drupal Association
  - [x] Positive, uplifting, and slightly horrifying [Drupal song](https://www.youtube.com/watch?v=lZ-s3DRZJKY) (for nostalgia's sake)
  - [x] Projects view migration (#45)
  - [ ] Redirect migration (#1)
  - [ ] Add configuration split (see #40)
  - [x] Home page migration (#44)

Video link: https://www.youtube.com/watch?v=pX_5k0mO3sU

**Comment by geerlingguy** [comment]
Mostly finished Projects and Home page migrations; will leave updates and notes in respective issues.
